### ISSUE TITLE
Prisma can't unfollow user

### ISSUE THREAD

**Issue by fridge7809** [DevOps-2024-group-p/maxitwit#25]
PrismaClientKnownRequestError:
Invalid `prisma.follower.delete()` invocation in
/usr/src/app/src/services/userService.js:253:52

  250
  251 async unfollowUser (userId, followedId) {
  252   try {
→ 253     const follower = await prisma.follower.delete(
An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
    at _n.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:123:6854)
    at _n.handleAndLogRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:123:6188)
    at _n.request (/usr/src/app/node_modules/@prisma/client/runtime/library.js:123:5896)
    at async l (/usr/src/app/node_modules/@prisma/client/runtime/library.js:128:10871)
    at async UserService.unfollowUser (/usr/src/app/src/services/userService.js:253:24)
    at async /usr/src/app/src/routes/api.js:179:7 {
  code: 'P2025',
  clientVersion: '5.10.2',
  meta: { modelName: 'Follower', cause: 'Record to delete does not exist.' }
}
Error: Error removing follower from database:
Invalid `prisma.follower.delete()` invocation in
/usr/src/app/src/services/userService.js:253:52

**Comment by fridge7809** [comment]
This is from prod.
